name: Vitals
version: 1.0.0
author: [Nelsin,Igorvanloo]
commands:
         Needs:
               description: Shows the developers for this server-mod
               usage: /<command>
         Tips:
              description: Shows the Tips for this server
              usage: /<command>
         Hello:
              description: Server says "hello" back
              usage: /<command
         Hi:
            description: Server says "hi" back
            usage: /<command>
         Hallo:
               description: Server says "hallo" back. German Version
               usage: /<command>
         
